version: '3.8'

services:

  postgres:
    image: postgres
    container_name: mini2_postgres
    environment:
      POSTGRES_DB: mini2
      POSTGRES_USER: mini2
      POSTGRES_PASSWORD: mini2
    ports:
      - "5432:5432"
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mini2_mongo
    ports:
      - "27017:27017"
    restart: unless-stopped

  mini2:
    build: .
    container_name: mini2_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mini2
      SPRING_DATASOURCE_USERNAME: mini2
      SPRING_DATASOURCE_PASSWORD: mini2
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/mini2_mongo
    restart: unless-stopped
